In [1]:
import torch

In [3]:
# New tensors are stored in main memory and designated for CPU-based computation by default
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# To get the total number of elements
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [9]:
X = x.reshape(3,4)
X
# because you can infer one dimension size you could have just used reshape(-1,4) or reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# To create a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0
# and standard deviation 1
torch.randn(3,4)

tensor([[ 0.9950,  1.2716, -1.2692,  0.4333],
        [ 0.2333,  1.4753, -0.8336,  0.3463],
        [ 1.3000, -1.8574, -0.7566, -0.5094]])